### ISSUE TITLE
You're doing a great job! 🎉

### ISSUE THREAD

**Issue by diragb** [hbatalhaStch/react-big-scheduler#16]
Just wanted to drop by and say that you're doing a fantastic job by maintaining this repository. I hope more people use your package, I sure will!

Let me know if I can support you in any way possible, I'm open to fixing bugs and maintaining this library on the side.

**Comment by hbatalhaStch** [comment]
> Just wanted to drop by and say that you're doing a fantastic job by maintaining this repository. I hope more people use your package, I sure will!

Thanks, I am really glad to hear that you find value in the repository.

> Let me know if I can support you in any way possible, I'm open to fixing bugs and maintaining this library on the side.

Thank you! Here are two of the immediate things I have in mind:
* Remove the need for users to install both react-dnd-html5-backend and react-dnd separately by streamlining the dependencies
* Convert this project to TypeScript (https://github.com/hbatalhaStch/react-big-scheduler/issues/12) but I haven't been able to get it started due to work

**Comment by ansulagrawal** [comment]
@diragb please check my repo too that has same funcationality @hbatalhaStch if you want we can merge your and my repo and make a org for same as I have fix more bugs and which your project also has. 

https://github.com/ansulagrawal/react-big-schedule please check it out

**Comment by hbatalhaStch** [comment]
>  if you want we can merge your and my repo and make a org for same as I have fix more bugs and which your project also has.

That is a great, let's have a meeting (in zoom, teams or discord, whichever you prefer) and discuss how to proceed to create the org?

**Comment by ansulagrawal** [comment]
Sure, please schedule a meeting.

**Comment by ansulagrawal** [comment]
@hbatalhaStch did you tried using you project in react with vite you project will not work. just test it out first

**Comment by hbatalhaStch** [comment]
> Sure, please schedule a meeting.

What about today (I usually have more time on weekends due to work during the week). hbatalha is my username in discord.

**Comment by hbatalhaStch** [comment]
> @hbatalhaStch did you tried using you project in react with vite you project will not work. just test it out first
> 
> 1. days locale
> 2. require is not allowed.

I haven't learned vite yet so I didn't try using it in react with vite.

**Comment by ansulagrawal** [comment]
vite is just a development environment configration similar to webpack.

**Comment by hbatalhaStch** [comment]
> vite is just a development environment configration similar to webpack.

I thought you were talking about this [vite](https://github.com/vitejs/vite)

**Comment by ansulagrawal** [comment]
yes that vite only

**Comment by hbatalhaStch** [comment]
@ansulagrawal I just went through your repo and realized you just copied my entire repo with this commit: https://github.com/ansulagrawal/react-big-schedule/commit/5007602cdcdc02ab8751d1eaf8a646d551a95eb3 and copying any new commit I make ever since.
And you haven't credited my repo in any way whatsoever. And I announced in this thread my intentions my plans to convert my project to TypeScript you went ahead and create [an issue  in your repo](https://github.com/ansulagrawal/react-big-schedule/issues/36#issue-1772595649) seeking to do the same.

Unfortunately I can't do anything to stop you from doing as my repo is public but I don't really appreciate the fact that you came on a post meant to congratulate me on my work in maintaining this fork and advertise your fork (which is basically a copy)

**Comment by diragb** [comment]
There is a special ring in hell for people who copy code and advertise it as their own. I'll be contributing code to this repo and keep a close eye on @ansulagrawal's copy. I'll also warn others I'm connected to that he's basically stealing code without crediting it. If @ansulagrawal wishes that that doesn't happen, he's free to delete his clone, or fork it, add his own commits, and credit the original.

At any rate, I wish this project all the success!

**Comment by ansulagrawal** [comment]
@diragb I have mention all who has contibuted to this as well as react-big-scheduler

**Comment by ansulagrawal** [comment]
@hbatalhaStch yes I have copied you code and impove it as much as I can.
Check in pr as well as change log I have mention you name as well.

**Comment by ansulagrawal** [comment]
@hbatalhaStch please check this alos: https://github.com/ansulagrawal/react-big-schedule/tree/readme-update

I am updating my readme in that same place is there for your and react-big-scheduler

**Comment by ansulagrawal** [comment]
The typescript I am littearly learning. I in a job user I get only free on saturday and sunday. So I can only give less time to the repo

**Comment by ansulagrawal** [comment]
![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/55939700/6ccc0361-5816-4e7d-864e-7c80537ce027)
Please check this also

**Comment by hbatalhaStch** [comment]
> There is a special ring in hell for people who copy code and advertise it as their own. I'll be contributing code to this repo and keep a close eye on @ansulagrawal's copy. I'll also warn others I'm connected to that he's basically stealing code without crediting it. If @ansulagrawal wishes that that doesn't happen, he's free to delete his clone, or fork it, add his own commits, and credit the original.
> 
> At any rate, I wish this project all the success!

Thank you

**Comment by hbatalhaStch** [comment]
@ansulagrawal that's not the proper way to give credit.

> @hbatalhaStch yes I have copied you code and impove it as much as I can. Check in pr as well as change log I have mention you name as well.

Mentioning my name in a PR does not notify me and it stays hidden away from the general GitHub public.

> @hbatalhaStch yes I have copied you code and impove it as much as I can. Check in pr as well as change log I have mention you name as well.

To be honest, I didn't see any improvement. I might be wrong, so feel free to point me any of these improvements.

> @hbatalhaStch please check this alos: https://github.com/ansulagrawal/react-big-schedule/tree/readme-update
> 
> I am updating my readme in that same place is there for your and react-big-scheduler

IMO, you should state that your repo is a fork (as it literally is) instead of citing my repo and original repo as just inspirations and contributors. When your first commit is with code from another repo, your repo is a fork and you state it is as such, that's how it is usually done. But this is just my personal opinion.

Words are very important so the way you arrange them sends different types of message. You should pay to attention to them.

> Please check this also

In your release change log you said that I suggested improvements (which in essence is not true as I coded all those changes), which indirectly says that I suggested improvements and you implemented those suggestions

Let's take a look at your latest(as of time of this writing) release changelog:

![Screenshot_2](https://github.com/hbatalhaStch/react-big-scheduler/assets/114578587/9744635d-5c7f-4bc0-ae0b-d1d292d2cab7)

The fix that is circled in red, you stated that it was done by you and @adam-m-clark when in reality that fix was completely done by him, every single line of code so IMO you shouldn't be crediting yourself in that fix as it is sending a different type of message. As I have said above, words are very important.

As of now, about 95% of changes/improvements that repo has when comparing to the original repo was done by me and the way you "credit" me simply doesn't reflect that.

I hope you take all of this as constructive criticism, which can make you a better (not in term of skills) open-source developer.

One suggestion, you should look to have a better understanding of how software versioning is done as I believe what you stating in your releases change log as breaking changes are not really breaking changes.

**Comment by ansulagrawal** [comment]
@hbatalhaStch thanks for the suggestion for the improvement I will update it

**Comment by ansulagrawal** [comment]
![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/55939700/f44a8205-5f76-40f5-86ee-76941fc8825f)
![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/55939700/62399c9d-97b7-4561-9de4-9595ad302c03)

@hbatalhaStch will this be fine or need to update anything more

**Comment by ansulagrawal** [comment]
![image](https://github.com/hbatalhaStch/react-big-scheduler/assets/55939700/2dc0bea7-0371-4185-bd2a-05faff880eba)

**Comment by diragb** [comment]
@ansulagrawal GitHub offers the *fork* feature - wondering why you didn't fork this repository but instead went to great lengths to copy over every single commit and not credit the original authors.

**Comment by ansulagrawal** [comment]
@diragb I didn't know about this repo earlier till I got message from him till then I just wanted to update package version and use it in my project which is running from last 1 year. I created a repo because when I updated my node version to 18 got multiple issue from the library so. I created my own repo with proper structuring and wanted to convert it to functional based totaly. Till now I have shifted many files to functional based still working on converting all files to it

**Comment by ansulagrawal** [comment]
If you still see there is difference in my repo as well as the way of using is slighty difference in mine

**Comment by diragb** [comment]
> Till now I have shifted many files to functional based still working on converting all files to it

@ansulagrawal Can you provide an example, and your motivation behind why you converted it to functional based?

**Comment by ansulagrawal** [comment]
I used to write the code in functional based and till now I meet many people they use functional based approch and in react if you see even the docs of react it uses functional based approch so

**Comment by diragb** [comment]
Can you provide an example?

**Comment by ansulagrawal** [comment]
example of the code where I have used or what?

**Comment by diragb** [comment]
> example of the code where I have used or what?

Yes, that is what I'm asking. Provide us examples of code present in this repository that you have converted to functional-based, and the exact reasoning behind why you have done so.

I don't think "everyone is doing that so I also did it" suffices, since there are major differences between how class based and functional based implementations work. In some cases, class based components are the only way we can implement something.

**Comment by ansulagrawal** [comment]
```js
import React, { useEffect, useReducer } from 'react';
import { useDispatch } from 'react-redux';
import { Scheduler, SchedulerData, ViewType, wrapperFun } from 'react-big-schedule';
import config from './scheduler.config';
import behaviorConfig from './behavior.config';
import { errorModal } from '../../helpers/modal-helper';
import randomValueGenerator from '../../helpers/random-value-generator';
import useWindowSize from '../../hooks/use-window-size.jsx';
import './index.scss';

let schedulerData;

const initialState = {
  showScheduler: false,
  viewModel: {},
};

function reducer(state, action) {
  switch (action.type) {
    case 'INITIALIZE':
      return { showScheduler: true, viewModel: action.payload };
    case 'UPDATE_SCHEDULER':
      return { ...state, viewModel: action.payload };
    default:
      return state;
  }
}

function SchedulerComponent(props) {
  const [state, dispatch] = useReducer(reducer, initialState);
  const sDispatch = useDispatch();
  const screen = useWindowSize();

  useEffect(() => {
    schedulerData = new SchedulerData(props.date, ViewType.Day, false, false, config(), behaviorConfig, undefined);
    schedulerData.localeDayjs.locale('en');

    schedulerData.setMinuteStep(30);

    schedulerData.setResources(props.resourceList || []);

    schedulerData.setEvents(props.eventList ?? []);

    if (props?.slot) {
      schedulerData.addEvent(props?.slot);
    }

    dispatch({ type: 'INITIALIZE', payload: schedulerData });
  }, [screen.height, screen.width]);

  const newEvent = (sd, slotId, slotName, start, end) => {
    // if (props.disableSlotClick) return;
    const oldEvent = schedulerData?.events?.find(ele => ele.type === 'temp');
    if (oldEvent) {
      schedulerData.removeEvent(oldEvent);
    }
    const event = {
      id: Math.floor(randomValueGenerator()),
      title: '',
      start,
      end,
      resourceId: slotId,
      type: 'temp',
    };
    schedulerData.addEvent(event);
    sDispatch(props?.changePilot?.(slotId));
    dispatch({ type: 'UPDATE_SCHEDULER', payload: schedulerData });
    props?.form.setFieldsValue({ header: { ...props?.form.getFieldValue('header'), start, end } });
    props.onChange?.(event);
  };

  const conflictOccurred = () => {
    errorModal(sDispatch, 'Please select a valid slot!', 'Slot Error', 'Warning');
  };

  const updateEventStart = (sd, event, newStart) => {
    if (event.type === 'temp') {
      schedulerData.updateEventStart(event, newStart);
      props?.form.setFieldsValue({ header: { ...props?.form.getFieldValue('header'), start: newStart } });
      dispatch({ type: 'UPDATE_SCHEDULER', payload: schedulerData });
    }
  };

  const updateEventEnd = (sd, event, newEnd) => {
    if (event.type === 'temp') {
      schedulerData.updateEventEnd(event, newEnd);
      props?.form.setFieldsValue({ header: { ...props?.form.getFieldValue('header'), end: newEnd } });
      dispatch({ type: 'UPDATE_SCHEDULER', payload: schedulerData });
    }
  };

  const eventItemTemplateResolver = (schData, event, bgColor, isStart, isEnd, mustAddCssClass) => {
    let additionalClass = '';

    if (event?.type && event.type === 'temp') {
      additionalClass = 'highlight-slot';
    }

    return (
      <div key={event.id} className={`${mustAddCssClass} ${additionalClass}`} style={{ background: bgColor }}>
        {event.title}
      </div>
    );
  };

  return (
    <div className="scheduler-component-wrapper">
      {state.showScheduler && (
        <div id="scheduler">
          <Scheduler
            schedulerData={state.viewModel}
            updateEventStart={updateEventStart}
            updateEventEnd={updateEventEnd}
            conflictOccurred={conflictOccurred}
            newEvent={newEvent}
            eventItemTemplateResolver={eventItemTemplateResolver}
          />
        </div>
      )}
    </div>
  );
}

export default wrapperFun(SchedulerComponent);

```

**Comment by ansulagrawal** [comment]
Example where I have used it

**Comment by ansulagrawal** [comment]
except `components/index.jsx`, `components/SchedulerData.js`, `components/HeaderView.jsx`, `components/DnDSource.js`, `components/DnDContext.js` all are function based

**Comment by ansulagrawal** [comment]
I need to updated examples also that I am currently working on it

**Comment by hbatalhaStch** [comment]
> @hbatalhaStch thanks for the suggestion for the improvement I will update it

Yes, it is alright now. Thank you!!

**Comment by hbatalhaStch** [comment]
@diragb  @ansulagrawal  what if we create an organization for this project and it would be completely in TypeScript and maybe functional components. What do you guys think?

**Comment by ansulagrawal** [comment]
Good Idea

**Comment by ansulagrawal** [comment]
I also want to get read of react-dnd as well as react-dnd-html5-backend. do you know any alternative of it?

**Comment by hbatalhaStch** [comment]
> I also want to get read of react-dnd as well as react-dnd-html5-backend. do you know any alternative of it?

Why do you want to get rid of react-dnd and react-dnd-html5-backend?

**Comment by ansulagrawal** [comment]
its older and its is not updated to the latest standards
